// src/app/terms/page.tsx
import Link from "next/link";

export default function TermsPage() {
  const year = new Date().getFullYear();

  return (
    <main className="min-h-screen bg-slate-950 text-slate-50">
      <section className="border-b border-slate-800 bg-slate-950">
        <div className="mx-auto max-w-3xl px-4 py-16 sm:py-20">
          <h1 className="text-3xl font-bold tracking-tight sm:text-4xl">
            Terms of Service
          </h1>
          <p className="mt-3 text-sm text-slate-300">Last updated: {year}</p>

          <p className="mt-6 text-sm text-slate-300">
            These Terms of Service (&quot;Terms&quot;) govern your use of{" "}
            <span className="font-semibold">Wanderwise AI</span> (&quot;we&quot;,
            &quot;us&quot;, &quot;our&quot;) and our website{" "}
            <span className="text-sky-300">https://wanderwise.uk</span> and
            related services (the &quot;Service&quot;). By accessing or using the
            Service, you agree to these Terms.
          </p>

          <p className="mt-4 text-xs text-slate-500">
            This document is a general template and not formal legal advice. For
            a fully compliant legal document, please consult a qualified lawyer.
          </p>

          {/* 1. Use of the service */}
          <section className="mt-10 space-y-3">
            <h2 className="text-xl font-semibold">1. Use of the Service</h2>
            <p className="text-sm text-slate-300">
              Wanderwise AI provides an AI-powered travel assistant that helps
              you plan trips, generate itineraries, and explore destinations. You
              agree to use the Service only for lawful purposes and in
              accordance with these Terms.
            </p>
          </section>

          {/* 2. Accounts */}
          <section className="mt-10 space-y-3">
            <h2 className="text-xl font-semibold">2. Accounts &amp; Security</h2>
            <p className="text-sm text-slate-300">
              To use certain features, you may need to create an account or sign
              in (for example, using your email or Google account). You are
              responsible for:
            </p>
            <ul className="list-disc space-y-2 pl-6 text-sm text-slate-300">
              <li>Maintaining the confidentiality of your login credentials.</li>
              <li>
                All activity that occurs under your account, whether or not
                authorized by you.
              </li>
            </ul>
            <p className="text-sm text-slate-300">
              If you suspect unauthorized access to your account, please notify
              us immediately at{" "}
              <a
                href="mailto:contact@wanderwise.uk"
                className="text-sky-300 underline hover:text-sky-400"
              >
                contact@wanderwise.uk
              </a>
              .
            </p>
          </section>

          {/* 3. Subscriptions */}
          <section className="mt-10 space-y-3">
            <h2 className="text-xl font-semibold">
              3. Subscriptions &amp; Billing
            </h2>
            <p className="text-sm text-slate-300">
              Wanderwise AI may offer free and paid subscription plans (for
              example weekly, monthly, or yearly). When you subscribe to a paid
              plan:
            </p>
            <ul className="list-disc space-y-2 pl-6 text-sm text-slate-300">
              <li>
                Payments are processed securely via our payment provider
                (Stripe).
              </li>
              <li>
                Your subscription will typically renew automatically at the end
                of each billing period unless you cancel before renewal.
              </li>
              <li>
                Prices, billing cycles, and features of each plan will be shown
                on our{" "}
                <Link
                  href="/pricing"
                  className="text-sky-300 underline hover:text-sky-400"
                >
                  Pricing
                </Link>{" "}
                page or inside the app.
              </li>
            </ul>
            <p className="text-sm text-slate-300">
              We may change plan prices or features over time. Where required, we
              will notify you in advance.
            </p>
          </section>

          {/* 4. AI-generated content */}
          <section className="mt-10 space-y-3">
            <h2 className="text-xl font-semibold">
              4. AI-Generated Content &amp; No Guarantees
            </h2>
            <p className="text-sm text-slate-300">
              The itineraries, suggestions, and answers provided by Wanderwise AI
              are generated by artificial intelligence. While we aim for high
              quality, we cannot guarantee that all information is accurate,
              complete, or up to date.
            </p>
            <p className="text-sm text-slate-300">
              You are responsible for independently verifying critical details
              such as visas, safety, opening hours, local laws, health
              requirements, and travel restrictions before booking or traveling.
            </p>
          </section>

          {/* 5. Acceptable use */}
          <section className="mt-10 space-y-3">
            <h2 className="text-xl font-semibold">5. Acceptable Use</h2>
            <p className="text-sm text-slate-300">
              You agree not to use the Service to:
            </p>
            <ul className="list-disc space-y-2 pl-6 text-sm text-slate-300">
              <li>Violate any applicable laws or regulations.</li>
              <li>
                Harass, abuse, or harm others, or promote hateful or illegal
                content.
              </li>
              <li>
                Attempt to reverse engineer, modify, or disrupt the Service or
                its infrastructure.
              </li>
              <li>
                Automate access in a way that overloads or interferes with our
                systems.
              </li>
            </ul>
          </section>

          {/* 6. IP */}
          <section className="mt-10 space-y-3">
            <h2 className="text-xl font-semibold">
              6. Intellectual Property &amp; License
            </h2>
            <p className="text-sm text-slate-300">
              The Wanderwise AI name, logo, design, and the underlying software
              and content (excluding user-generated content) are owned by us or
              our licensors and are protected by copyright, trademark, and other
              laws.
            </p>
            <p className="text-sm text-slate-300">
              We grant you a limited, non-exclusive, non-transferable license to
              use the Service for personal, non-commercial travel planning
              purposes, subject to these Terms.
            </p>
          </section>

          {/* 7. Third-party services */}
          <section className="mt-10 space-y-3">
            <h2 className="text-xl font-semibold">
              7. Third-Party Services &amp; Links
            </h2>
            <p className="text-sm text-slate-300">
              The Service may link to third-party websites or services (for
              example booking sites, maps, or payment providers). We do not
              control and are not responsible for the content, policies, or
              practices of these third parties.
            </p>
          </section>

          {/* 8. Disclaimer */}
          <section className="mt-10 space-y-3">
            <h2 className="text-xl font-semibold">
              8. Disclaimer of Warranties
            </h2>
            <p className="text-sm text-slate-300">
              The Service is provided on an &quot;AS IS&quot; and &quot;AS
              AVAILABLE&quot; basis. To the fullest extent permitted by law, we
              disclaim all warranties, express or implied, including
              merchantability, fitness for a particular purpose, and
              non-infringement.
            </p>
          </section>

          {/* 9. Limitation of liability */}
          <section className="mt-10 space-y-3">
            <h2 className="text-xl font-semibold">
              9. Limitation of Liability
            </h2>
            <p className="text-sm text-slate-300">
              To the maximum extent permitted by law, we are not liable for any
              indirect, incidental, special, consequential, or punitive damages,
              or any loss of profits or data, arising out of or related to your
              use of the Service.
            </p>
          </section>

          {/* 10. Termination */}
          <section className="mt-10 space-y-3">
            <h2 className="text-xl font-semibold">10. Termination</h2>
            <p className="text-sm text-slate-300">
              We may suspend or terminate your access to the Service if you
              violate these Terms or if we decide to discontinue the Service.
              You may stop using the Service at any time by closing your account
              or canceling your subscription.
            </p>
          </section>

          {/* 11. Changes */}
          <section className="mt-10 space-y-3">
            <h2 className="text-xl font-semibold">
              11. Changes to These Terms
            </h2>
            <p className="text-sm text-slate-300">
              We may update these Terms from time to time. When we do, we will
              update the &quot;Last updated&quot; date above. Your continued use
              of the Service after changes become effective constitutes your
              acceptance of the new Terms.
            </p>
          </section>

          {/* 12. Contact */}
          <section className="mt-10 space-y-3">
            <h2 className="text-xl font-semibold">12. Contact Us</h2>
            <p className="text-sm text-slate-300">
              If you have questions about these Terms, please contact us at:
            </p>
            <p className="text-sm text-slate-300">
              Email:{" "}
              <a
                href="mailto:contact@wanderwise.uk"
                className="text-sky-300 underline hover:text-sky-400"
              >
                contact@wanderwise.uk
              </a>
            </p>
          </section>

          <div className="mt-10">
            <Link
              href="/"
              className="text-sm text-sky-300 underline hover:text-sky-400"
            >
              ← Back to home
            </Link>
          </div>
        </div>
      </section>
    </main>
  );
}


